#This script has only been tested on OpenSuSE SLES 15.
#This script should execute properly as long as yp.conf, auto.master, and nsswitch.conf is in /etc.
#Author - Parker Schoenig
#Parker.Schoenig@dell.com

import paramiko
import socket
import getpass
import time

print('This script will configure yp.conf, auto.master, and nsswitch.conf')

time.sleep(1)
host = input('Enter IP: ')
username = input('login as: ')
password = getpass.getpass(username + '@' + host + '\x27s password: ')
print("")
print('Checking network on ' + host)
time.sleep(2)
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
result = sock.connect_ex((host, 22))
if result == 0:
    print(host + ' is alive, establishing connection')
    try:
        p = paramiko.SSHClient()
        p.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        p.connect(host, username=username, password=password)
        print('Connected to ' + host)
        time.sleep(2)
        print("Configuring yp.conf...")
        p_stdin, p_stdout, p_stderr = p.exec_command('echo "### /etc/yp.conf file autogenerated by netconfig!\n"'
                        + '"#\n"'
                        + '"# Before you change this file manually, consider to define the\n"'
                        + '"# static NIS configuration using the following variables in the\n"'
                        + '"# /etc/sysconfig/network/config file:\n"'
                        + '"#     NETCONFIG_NIS_STATIC_DOMAIN[_<number>]\n"'
                        + '"#     NETCONFIG_NIS_STATIC_SERVERS[_<number>]\n"'
                        + '"# or disable NIS configuration updates via netconfig by setting:\n"'
                        + '"#     NETCONFIG_NIS_POLICY=\n"'
                        + '"#\n"'
                        + '"# See also the netconfig(8) manual page and other documentation.\n"'
                        + '"#\n"'
                        + '"# Note: Manual change of this file disables netconfig too, but\n"'
                        + '"# may get lost when this file contains comments or empty lines\n"'
                        + '"# only, the netconfig settings are same with settings in this\n"'
                        + '"# file and in case of a "netconfig update -f" call.\n"'
                        + '"#\n"'
                        + '"### Please remove (at least) this line when you modify the file!\n"'
                        + '"domain <domain name> server 11.22.33.44"' #Enter your NIS server information here
                        + ' > /etc/yp.conf')
        print("yp.conf has been configured.")
        time.sleep(1)
        print("Configuring auto.master...")
        p_stdin, p_stdout, p_stderr = p.exec_command('echo "### /etc/yp.conf file autogenerated by netconfig!\n"'
                        + '"#\n"'
                        + '"# Sample auto.master file\n"'
                        + '"# This is a master automounter map and it has the following format:\n"'
                        + '"# mount-point [map-type[,format]:]map [options]\n"'
                        + '"# For details of the format look at auto.master(5).\n"'
                        + '"#\n"'
                        + '"# /misc  /etc/auto.misc\n"'
                        + '"#\n"'
                        + '"# NOTE: mounts done from a hosts map will be mounted with the\n"'
                        + '"#      "nosuid" and "nodev" options unless the "suid" and "dev"\n"'
                        + '"#       options are explicitly given."'
                        + '"#\n"'
                        + '"#/net   -hosts\n"'
                        + '"#\n"'
                        + '"# Include /etc/auto.master.d/*.autofs\n"'
                        + '"# The included files must conform to the format of this file.\n"'
                        + '"#\n"'
                        + '"# +dir:/etc/auto.master.d\n"'
                        + '"#\n"'
                        + '"# Include central master map if it can be found using\n"'
                        + '"# nsswitch sources.\n"'
                        + '"#\n"'
                        + '"# Note that if there are entries for /net or /misc (as\n"'
                        + '"# above) in the included master map any keys that are the\n"'
                        + '"# same will not be seen as the first read key seen takes\n"'
                        + '"# precedence.\n"'
                        + '"#\n"'
                        + '"/usr/local -null\n"'
                        + '"+auto.master"'
                        + ' > /etc/auto.master')
        print("auto.master has been configured.")
        time.sleep(1)
        print("Configuring nsswitch.conf...")
        p_stdin, p_stdout, p_stderr = p.exec_command('echo "#\n"'
                       + '"# /etc/nsswitch.conf\n"'
                       + '"# Legal entries are:\n"'
                       + '"#\n"'
                       + '"#       compat                  Use compatibility setup\n"'
                       + '"#       nisplus                 Use NIS+ (NIS version 3\n"'
                       + '"#       nis                     Use NIS (NIS version 2), also called YP\n"'
                       + '"#       dns                     Use DNS (Domain Name Service)\n"'
                       + '"#       files                   Use the local files\n"'
                       + '"#       [NOTFOUND=return]       Stop searching if not found so far\n"'
                       + '"#\n"'
                       + '"# For more information, please read the nsswitch.conf.5 manual page.\n"'
                       + '"#\n"'
                       + '"passwd: files nis\n"'
                       + '"group:  files nis\n"'
                       + '"shadow: files nis\n"'
                       + '"\n"'
                       + '"hosts:  files dns nis\n"'
                       + '"networks:       files\n"'
                       + '"\n"'
                       + '"services:       files\n"'
                       + '"protocols:      files\n"'
                       + '"rpc:    files\n"'
                       + '"netmasks:       files\n"'
                       + '"netgroup:       files nis\n"'
                       + '"publickey:      nisplus\n"'
                       + '"\n"'
                       + '"bootparams:     nisplus [NOTFOUND=return] files\n"'
                       + '"automount:      nis\n"'
                       + '"aliases:        files nisplus"'
                       + ' > /etc/nsswitch.conf')
        print("nsswitch.conf has been configured.")
        time.sleep(1)
        p.close()
    except paramiko.AuthenticationException:
        print('Wrong credentials for ' + host)
        print('Could not change suffixes')
        print('Closing application in 10 seconds, please wait')
        time.sleep(10)


else:
    print('Unable to connect to ' + host + '. Please check network.')
    print('Closing application in 10 seconds, please wait')
    time.sleep(10)


print('All files configured. Exiting in 5 seconds, please wait')
time.sleep(5)
